name: Remote SSH Command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: DEPLOY
    steps:
      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/miranda
            git pull origin main
            sudo composer install
            sudo php artisan migrate
            sudo npm install
            sudo service apache2 restart
